version: "3.3"

networks:
  vgv-network:

services:
  vgv-db:
    container_name: vgv-db
    image: postgres:14.2
    env_file: .env
    networks:
      - vgv-network
    ports:
      - "5555:5432"

  vgv-adminer:
    container_name: vgv-adminer
    image: adminer:4.8.1
    env_file: .env
    networks:
      - vgv-network
    ports:
      - "81:8080"